source 'https://rubygems.org'

gem 'sinatra', '~> 3.2.0', require: false
gem 'sinatra-contrib'
gem 'activerecord', '< 7.1.0'
gem 'sinatra-activerecord'
# xxx to avoid error around ActiveSupport::LoggerThreadSafeLevel::Logger
gem 'concurrent-ruby', '< 1.3.5'
gem 'sqlite3', '~> 1.4'
gem 'bcrypt'
gem 'rake'
gem 'pry'

group :production do
  gem 'passenger'
end
