source 'https://rubygems.org'

gem 'sinatra', '~> 3.2.0', require: false
gem 'sinatra-contrib'
gem 'activerecord', '< 7.1.0'
gem 'sinatra-activerecord'
gem 'sqlite3', '~> 1.4.0'
gem 'bcrypt'
gem 'rake'
gem 'pry'

group :production do
  gem 'passenger'
end
