source 'https://rubygems.org'

gem 'sinatra', '~> 4.0', '>= 4.1.1', require: false
gem 'sinatra-contrib'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'sqlite3'
gem 'bcrypt'
gem 'rake', require: false
gem 'pry', require: false

group :production do
  gem 'passenger', require: false
end

group :development do
  gem 'rackup', require: false
  gem 'webrick', require: false
end
